MVMString * MVM_string_utf16_decode(struct MVMThreadContext *tc, const MVMObject *result_type, char *utf16, size_t bytes);
MVMString * MVM_string_utf16le_decode(struct MVMThreadContext *tc, const MVMObject *result_type, char *utf16, size_t bytes);
MVMString * MVM_string_utf16be_decode(struct MVMThreadContext *tc, const MVMObject *result_type, char *utf16, size_t bytes);
char * MVM_string_utf16_encode_substr(struct MVMThreadContext *tc, MVMString *str, uint64_t *output_size, int64_t start, int64_t length, MVMString *replacement, int32_t translate_newlines);
char * MVM_string_utf16le_encode_substr(struct MVMThreadContext *tc, MVMString *str, uint64_t *output_size, int64_t start, int64_t length, MVMString *replacement, int32_t translate_newlines);
char * MVM_string_utf16be_encode_substr(struct MVMThreadContext *tc, MVMString *str, uint64_t *output_size, int64_t start, int64_t length, MVMString *replacement, int32_t translate_newlines);
char * MVM_string_utf16_encode(struct MVMThreadContext *tc, MVMString *str, int32_t translate_newlines);
uint32_t MVM_string_utf16_decodestream(struct MVMThreadContext *tc, MVMDecodeStream *ds, const uint32_t *stopper_chars, MVMDecodeStreamSeparators *seps);
uint32_t MVM_string_utf16le_decodestream(struct MVMThreadContext *tc, MVMDecodeStream *ds, const uint32_t *stopper_chars, MVMDecodeStreamSeparators *seps);
uint32_t MVM_string_utf16be_decodestream(struct MVMThreadContext *tc, MVMDecodeStream *ds, const uint32_t *stopper_chars, MVMDecodeStreamSeparators *seps);
