MVMObject * MVM_thread_new(struct MVMThreadContext *tc, MVMObject *invokee, int64_t app_lifetime);
void MVM_thread_run(struct MVMThreadContext *tc, MVMObject *thread);
void MVM_thread_join(struct MVMThreadContext *tc, MVMObject *thread);
int64_t MVM_thread_id(struct MVMThreadContext *tc, MVMObject *thread);
int64_t MVM_thread_native_id(struct MVMThreadContext *tc, MVMObject *thread);
int64_t MVM_thread_current_os_thread_id(struct MVMThreadContext *tc);
void MVM_thread_yield(struct MVMThreadContext *tc);
MVMObject * MVM_thread_current(struct MVMThreadContext *tc);
int64_t MVM_thread_lock_count(struct MVMThreadContext *tc, MVMObject *thread);
int32_t MVM_thread_cleanup_threads_list(struct MVMThreadContext *tc, MVMThread **head);
void MVM_thread_join_foreground(struct MVMThreadContext *tc);
void MVM_thread_set_self_name(struct MVMThreadContext *tc, MVMString *name);
